<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <BroilerUiVersion>0.1.0-preview.18</BroilerUiVersion>
    <BroilerGraphicsVersion>0.1.0-preview.7</BroilerGraphicsVersion>
    <BroilerNativeVersion>0.1.0-preview.6</BroilerNativeVersion>
    <BroilerInputVersion>0.1.0-preview.5</BroilerInputVersion>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="Broiler.UI" Version="$(BroilerUiVersion)" />
    <PackageVersion Include="Broiler.UI.Standard" Version="$(BroilerUiVersion)" />
    <PackageVersion Include="Broiler.UI.Button" Version="$(BroilerUiVersion)" />
    <PackageVersion Include="Broiler.UI.Button.Standard" Version="$(BroilerUiVersion)" />
    <PackageVersion Include="Broiler.UI.ComboBox" Version="$(BroilerUiVersion)" />
    <PackageVersion Include="Broiler.UI.ComboBox.Standard" Version="$(BroilerUiVersion)" />
    <PackageVersion Include="Broiler.UI.Edit" Version="$(BroilerUiVersion)" />
    <PackageVersion Include="Broiler.UI.Label.Standard" Version="$(BroilerUiVersion)" />
    <PackageVersion Include="Broiler.UI.Edit.Standard" Version="$(BroilerUiVersion)" />
    <PackageVersion Include="Broiler.UI.FormatCodeView.Standard" Version="$(BroilerUiVersion)" />
    <PackageVersion Include="Broiler.UI.ListView" Version="$(BroilerUiVersion)" />
    <PackageVersion Include="Broiler.UI.ListView.Standard" Version="$(BroilerUiVersion)" />
    <PackageVersion Include="Broiler.UI.Panel.Standard" Version="$(BroilerUiVersion)" />
    <PackageVersion Include="Broiler.UI.RichEdit" Version="$(BroilerUiVersion)" />
    <PackageVersion Include="Broiler.UI.RichEdit.Standard" Version="$(BroilerUiVersion)" />
    <PackageVersion Include="Broiler.UI.SpinBox.Standard" Version="$(BroilerUiVersion)" />
    <PackageVersion Include="Broiler.UI.TabView" Version="$(BroilerUiVersion)" />
    <PackageVersion Include="Broiler.UI.TabView.Standard" Version="$(BroilerUiVersion)" />
    <PackageVersion Include="Broiler.UI.ToggleButton.Standard" Version="$(BroilerUiVersion)" />
    <PackageVersion Include="Broiler.UI.Toolbar.Standard" Version="$(BroilerUiVersion)" />
    <PackageVersion Include="Broiler.Graphics" Version="$(BroilerGraphicsVersion)" />
    <PackageVersion Include="Broiler.Graphics.Windows" Version="$(BroilerGraphicsVersion)" />
    <PackageVersion Include="Broiler.Graphics.Linux" Version="$(BroilerGraphicsVersion)" />
    <PackageVersion Include="Broiler.Graphics.Linux.OpenGL" Version="$(BroilerGraphicsVersion)" />
    <PackageVersion Include="Broiler.Graphics.Android" Version="$(BroilerGraphicsVersion)" />
    <PackageVersion Include="Broiler.Native" Version="0.1.0-preview.7" />
    <PackageVersion Include="Broiler.Native.Windows" Version="0.1.0-preview.7" />
    <PackageVersion Include="Broiler.Native.Linux" Version="0.1.0-preview.7" />
    <PackageVersion Include="Broiler.Native.Android" Version="$(BroilerNativeVersion)" />
    <PackageVersion Include="Broiler.Input" Version="$(BroilerInputVersion)" />
    <PackageVersion Include="Broiler.Input.Keyboard" Version="$(BroilerInputVersion)" />
    <PackageVersion Include="Broiler.Input.Keyboard.Windows" Version="$(BroilerInputVersion)" />
    <PackageVersion Include="Broiler.Input.Keyboard.Linux" Version="$(BroilerInputVersion)" />
    <PackageVersion Include="Broiler.Input.Keyboard.Android" Version="$(BroilerInputVersion)" />
    <PackageVersion Include="Broiler.Input.Mouse" Version="$(BroilerInputVersion)" />
    <PackageVersion Include="Broiler.Input.Mouse.Windows" Version="$(BroilerInputVersion)" />
    <PackageVersion Include="Broiler.Input.Mouse.Linux" Version="$(BroilerInputVersion)" />
    <PackageVersion Include="Broiler.Input.Pen" Version="$(BroilerInputVersion)" />
    <PackageVersion Include="Broiler.Input.Pen.Android" Version="$(BroilerInputVersion)" />
    <PackageVersion Include="Broiler.Input.Text" Version="$(BroilerInputVersion)" />
    <PackageVersion Include="Broiler.Input.Text.Android" Version="$(BroilerInputVersion)" />
    <PackageVersion Include="Broiler.Input.Touch" Version="$(BroilerInputVersion)" />
    <PackageVersion Include="Broiler.Input.Touch.Android" Version="$(BroilerInputVersion)" />
    <PackageVersion Include="Broiler.Input.Linux" Version="$(BroilerInputVersion)" />
    <PackageVersion Include="Broiler.Input.Android" Version="$(BroilerInputVersion)" />
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="18.0.1" />
    <PackageVersion Include="xunit" Version="2.9.3" />
    <PackageVersion Include="xunit.runner.visualstudio" Version="3.1.5" />
  </ItemGroup>
</Project>