<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <NoWarn>$(NoWarn);CA1416</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Broiler.Hosting.Windows\Broiler.Hosting.Windows.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <PackageReference Include="Broiler.UI.Standard" />
    <PackageReference Include="Broiler.UI.Button.Standard" />
    <PackageReference Include="Broiler.UI.ComboBox.Standard" />
    <PackageReference Include="Broiler.UI.Edit.Standard" />
    <PackageReference Include="Broiler.UI.Forms.Standard" />
    <PackageReference Include="Broiler.UI.Label.Standard" />
    <PackageReference Include="Broiler.UI.Panel.Standard" />
    <PackageReference Include="Broiler.UI.RichEdit.Standard" />
    <PackageReference Include="Broiler.UI.ScrollView.Standard" />
    <PackageReference Include="Broiler.UI.ToggleButton.Standard" />
  </ItemGroup>
</Project>
